name: Build Telegram Account Converter (Cross Platform)

on:
  push:
    branches:
      - main

jobs:
  build-mac-m1:
    name: Build macOS ARM (M1/M2)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Clean old builds
        run: |
          rm -rf dist build *.spec TelegramAccountConverter.app

      - name: Build macOS App
        run: |
          pyinstaller \
            --name=TelegramAccountConverter \
            --windowed \
            --add-data="gui.py:." \
            --add-data="converter.py:." \
            main.py

      - name: Package to ZIP
        run: |
          mkdir -p TelegramAccountConverter-mac-arm64
          cp -R dist/TelegramAccountConverter.app TelegramAccountConverter-mac-arm64/
          zip -r TelegramAccountConverter-mac-arm64.zip TelegramAccountConverter-mac-arm64

      - name: Upload via transfer.sh
        id: upload-mac
        run: |
          FILENAME="TelegramAccountConverter-mac-arm64.zip"
          URL=$(curl --upload-file "./$FILENAME" https://transfer.sh/$FILENAME)
          echo "::set-output name=url::$URL"

      - name: Print Download Link
        run: |
          echo "✅ macOS ARM 构建完成，下载地址: ${{ steps.upload-mac.outputs.url }}"

  build-windows:
    name: Build Windows x64 EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Clean old builds
        run: |
          rmdir /s /q dist build
          del *.spec

      - name: Build Windows EXE
        run: |
          pyinstaller ^
            --name=TelegramAccountConverter ^
            --onefile ^
            --add-data="gui.py;." ^
            --add-data="converter.py;." ^
            main.py

      - name: Package to ZIP
        run: |
          mkdir TelegramAccountConverter-win-x64
          copy dist\TelegramAccountConverter.exe TelegramAccountConverter-win-x64\
          powershell Compress-Archive -Path TelegramAccountConverter-win-x64 -DestinationPath TelegramAccountConverter-win-x64.zip -Force

      - name: Upload via transfer.sh
        id: upload-win
        run: |
          curl.exe -F "file=@TelegramAccountConverter-win-x64.zip" https://transfer.sh/TelegramAccountConverter-win-x64.zip > download_url.txt
          set /p DOWNLOAD_URL=<download_url.txt
          echo "::set-output name=url::$DOWNLOAD_URL"

      - name: Print Download Link
        run: |
          echo "✅ Windows x64 构建完成，下载地址: ${{ steps.upload-win.outputs.url }}"