name: Build Telegram Account Converter (Push to download Branch)

on:
  push:
    branches:
      - main

jobs:
  build-mac-m1:
    name: Build macOS ARM (M1/M2)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Clean old builds
        run: |
          rm -rf dist build *.spec TelegramAccountConverter.app

      - name: Build macOS App
        run: |
          pyinstaller \
            --name=TelegramAccountConverter \
            --windowed \
            --add-data="gui.py:." \
            --add-data="converter.py:." \
            main.py

      - name: Package to ZIP
        run: |
          mkdir -p TelegramAccountConverter-mac-arm64
          cp -R dist/TelegramAccountConverter.app TelegramAccountConverter-mac-arm64/
          zip -r TelegramAccountConverter-mac-arm64.zip TelegramAccountConverter-mac-arm64

      - name: Push to download Branch (macOS)
        uses: azure/push-to-deploy@v1
        with:
          target-folder: .
          source-folder: TelegramAccountConverter-mac-arm64.zip
          branch: download
          repository-name: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Update macOS build'

  build-windows:
    name: Build Windows x64 EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Clean old builds
        run: |
          Remove-Item -Recurse -Force dist, build -ErrorAction SilentlyContinue
          Remove-Item *.spec -ErrorAction SilentlyContinue

      - name: Build Windows EXE
        run: |
          pyinstaller --name=TelegramAccountConverter --onefile --add-data="gui.py;." --add-data="converter.py;." main.py

      - name: Package to ZIP
        run: |
          mkdir TelegramAccountConverter-win-x64
          copy dist\TelegramAccountConverter.exe TelegramAccountConverter-win-x64\
          Compress-Archive -Path TelegramAccountConverter-win-x64 -DestinationPath TelegramAccountConverter-win-x64.zip -Force

      - name: Push to download Branch (Windows)
        uses: azure/push-to-deploy@v1
        with:
          target-folder: .
          source-folder: TelegramAccountConverter-win-x64.zip
          branch: download
          repository-name: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Update Windows build'